# GitHub Pages Configuration for Veda Hospital

# Site settings
title: "Veda Hospital"
description: "Putting your healing needs first. High quality healthcare service, medical experience, and commitment to health and wellness."
url: "https://yourusername.github.io"
baseurl: "/veda-hospital"

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: "Veda Hospital"
twitter:
  username: vedahospital
facebook:
  app_id: 1234567890
  publisher: https://www.facebook.com/vedahospital

# Theme (optional - can be removed for custom styling)
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Include files in processing
include:
  - _headers
  - _redirects

# Collections (if needed for blog/news)
collections:
  news:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Social media
social:
  - name: facebook
    url: https://www.facebook.com/vedahospital
  - name: twitter  
    url: https://twitter.com/vedahospital
  - name: linkedin
    url: https://www.linkedin.com/company/vedahospital

# Contact information
contact:
  phone: ["+91-7901228989", "+91-7302938979"]
  email: "info@vedahospital.com"
  address: "Veda Hospital, India"

# Hospital information
hospital:
  name: "Veda Hospital"
  tagline: "Putting your healing needs first"
  established: "2020"
  specialties:
    - "General Medicine"
    - "Emergency Care"  
    - "Diagnostic Services"
    - "Surgical Procedures"
    - "Preventive Care"
    - "Health Checkups"
